name: Run Unit Tests

on:
  push:
    branches:
      - lab_4  # или main, если нужно
  pull_request:
    branches:
      - lab_4  # или main, если нужно

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt file found"

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"
